version: '3.8'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8.0'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:3.4.0-debian-11-r0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

#   mongo:
#     image: mongo:latest
#     container_name: mongo_container
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

#   user-service:
#     build: ./services/user-service
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/userdb
#     depends_on:
#       - mongo
#     ports:
#       - "5001:5001"

#   product-service:
#     build: ./services/product-service
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/productdb
#     depends_on:
#       - mongo
#     ports:
#       - "5002:5002"

#   order-service:
#     build: ./services/order-service
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/orderdb
#     depends_on:
#       - mongo
#     ports:
#       - "5003:5003"

# volumes:
#   mongo_data:
